UniqueNetwork/unique-new-wallet

.eslintrc.js, .prettierrc, .prettierrc.js, src/pages/CollectionSettings/CollectionSettings.tsx, src/pages/CollectionSettings/index.ts, src/routesConfig.tsx
https://cryptousetech.atlassian.net/browse/WMS-860
=> Add collection settings page

package.json, src/components/DropdownMenu/DropdownMenu.tsx, src/components/DropdownMenu/types.ts, src/components/Filters/MobileFilter.tsx, src/components/MobileTable/MobileTable.tsx, src/components/Table.tsx, src/pages/Accounts/Accounts.tsx, src/pages/Accounts/Modals/AskCredentials.tsx, src/pages/Accounts/Modals/AskExistsSeedPhrase.tsx, src/pages/Accounts/Modals/Final.tsx, src/pages/Accounts/Modals/ImportViaSeed.tsx, src/pages/Accounts/Modals/commonComponents.tsx, src/pages/MyCollections/components/MyCollectionsList/MyCollectionsList.tsx, src/pages/Welcome/Welcome.tsx, yarn.lock
- Modal markup using uikit components.
=> [WMS-865] modal: add via seed phrase.

src/api/graphQL/tokens/types.ts, src/pages/Accounts/Modals/AskSeedPhrase.tsx, src/pages/Accounts/Modals/CreateAccount.tsx
=> [WMS-864] create account modal

src/components/Confirm/Confirm.tsx, src/components/Confirm/index.ts, src/components/index.ts, src/pages/Accounts/Accounts.tsx, src/pages/Accounts/components/AccountContextMenu.tsx
- Add confirm modal in accounts page;
- fix deleted no-collections.svg;
- small fix account dropdown.
=> [WMS-875] Universal confirm modal.

src/pages/FAQ/components/FaqItems.tsx, src/pages/FAQ/components/Plate.tsx, src/pages/FAQ/index.tsx
- Link name;
- expand 1st list item;
- titles color.
=> [WAL-63] FAQ page bugfix.

src/pages/Accounts/Modals/AskCredentials.tsx, src/pages/Accounts/Modals/AskExistsSeedPhrase.tsx, src/pages/Accounts/Modals/AskSeedPhrase.tsx, src/pages/Accounts/Modals/Final.tsx, src/pages/Accounts/Modals/ImportViaSeed.tsx, src/pages/Accounts/Modals/commonComponents.tsx
- Address wrapper placeholder;
- add form label.
=> [WAL-53] Modal add account via seed phrase

src/api/restApi/hooks/useExtrinsicFee/extrinsicFeeReducer.ts, src/api/restApi/hooks/useExtrinsicFee/useExtrinsicFee.ts, src/components/TooltipWrapper/TooltipWrapper.tsx, src/components/TooltipWrapper/index.ts, src/components/index.ts, src/hooks/index.ts, src/hooks/useBalanceInsufficient.ts, src/hooks/useFee.ts, src/pages/CreateCollection/pages/MainInformation.tsx, src/pages/CreateCollection/pages/NFTAttributes.tsx, src/pages/CreateNFT/CreateNFT.tsx, src/pages/NFTDetails/Modals/BurnModal/AskBurnModal.tsx, src/pages/NFTDetails/Modals/TransferModal/AskTransferModal.tsx, src/pages/NFTDetails/Modals/TransferModal/TransferModal.tsx, src/pages/components/FormComponents.tsx, src/pages/constants.ts, src/pages/index.ts
- Add tooltip wrapper;
- get whole fee (exclude unit) from useFee hook.
=> [WAL-397] - Disable minting button when insufficient funds

src/components/PageLayout/PageLayout.tsx, src/pages/Accounts/Accounts.tsx, src/pages/MyCollections/components/MyCollectionsFilter/MyCollectionsFilter.tsx, src/pages/MyTokens/MyTokens.tsx
- My tokes page;
- my accounts page.
=> [WAL-375] Page headings.

package.json, src/components/ActionBtn/BaseActionBtn.tsx, src/components/TooltipWrapper/TooltipWrapper.tsx, src/pages/Accounts/Accounts.tsx, src/pages/Accounts/Modals/Final.tsx, src/pages/Accounts/Modals/commonComponents.tsx, src/pages/CollectionPage/components/CollectionNftFilters/CollectionNftFilters.tsx, src/pages/CollectionPage/pages/CollectionSettings/CollectionSettings.tsx, src/pages/CreateCollection/pages/NFTAttributes.tsx, src/pages/CreateCollection/pages/components/AttributesTable.tsx, src/pages/CreateNFT/CreateNFT.tsx, src/pages/MyCollections/components/MyCollectionsFilter/MyCollectionsFilter.tsx, src/pages/MyCollections/components/MyCollectionsList/MyCollectionsList.tsx, src/pages/MyTokens/NFTs/components/NFTFilters/NFTFilters.tsx, src/pages/components/FormComponents.tsx, src/pages/components/Nfts/NFTsTemplateList/NFTsTemplateList.tsx
- Change CollectionLink, Tooltips props using 0.0.29 kit.
=> [WAL-424] CollectionLink, Tooltips.

src/pages/components/Card/Card.tsx
- Fix text overflow in sidebar.
=> [WAL-420] Create collection page sidebar.

src/components/CollectionScanLink/CollectionScanLink.tsx, src/pages/CollectionNft/components/CollectionDescription/CollectionDescription.tsx, src/pages/CreateCollection/pages/components/AttributesTable.tsx
- Sidebar;
- attributes table - table thead padding.
=> [WAL-377] Collection NFTs page.

src/App/App.tsx
- Add useEffect for set current chain.
=> Fix App rendering.

src/pages/CreateCollection/CreateCollection.tsx, src/pages/CreateNFT/CreateNFT.tsx
- Create NFT;
- create collection.
=> Add headings to pages.

package.json, src/components/Header/Header.tsx, src/components/Header/WalletManager/WalletManager.tsx, src/components/IdentityIcon/IdentityIcon.tsx, src/components/IdentityIcon/index.ts, src/components/SignModal/SignModal.tsx, src/components/Table.tsx, src/components/index.ts, src/pages/Accounts/Accounts.tsx, src/pages/Accounts/Modals/AskCredentials.tsx, src/pages/Accounts/Modals/AskExistsSeedPhrase.tsx, src/pages/Accounts/Modals/AskSeedPhrase.tsx, src/pages/Accounts/Modals/Final.tsx, src/pages/Accounts/Modals/ImportViaQRCode.tsx, src/pages/Accounts/components/AccountCard.tsx, src/pages/NFTDetails/components/NFTDetailsHeader.tsx, src/pages/SendFunds/components/AccountInfo.tsx, src/pages/SendFunds/components/AccountSuggest.tsx, src/pages/SendFunds/components/Style.tsx, src/pages/components/Nfts/NFTsTemplateList/NFTsTemplateList.tsx
=> feat: [WAL-319] - add generated account avatar.

src/components/NoItems.tsx, src/pages/MyCollections/components/MyCollectionsList/MyCollectionsList.tsx, src/pages/components/Nfts/NFTsTemplateList/NFTsTemplateList.tsx
=> fix: [WAL-452] - No items title.

src/components/TokenLink/TokenLink.tsx, src/pages/MyCollections/components/MyCollectionsList/MyCollectionsList.tsx, src/pages/components/Nfts/NFTsTemplateList/NFTsTemplateList.tsx, src/pages/components/PageComponents.tsx, src/routes.ts
- Local common TokenLink component;
- fix tokens & collections grids.
=> fix: [WAL-419] - My Collections grid

src/pages/MyTokens/NFTs/NFTs.tsx, src/pages/MyTokens/NFTs/components/CollectionsFilter/CollectionFilter.tsx, src/pages/MyTokens/NFTs/components/CollectionsFilter/CollectionFilterItem.tsx, src/utils/address.ts
=> fix: [WAL-495] - Show emptyImage, when its broken.

src/App/App.tsx, src/AppRoutes.tsx, src/api/ApiWrapper.tsx, src/components/Header/Header.tsx, src/pages/MyCollections/MyCollections.tsx
=> fix: [WAL-493] - url of the current network is incorrect change

src/components/AccountsGroupButton/AccountsGroupButton.tsx, src/components/MobileTable/MobileTable.tsx, src/components/NoItems.tsx, src/components/Table.tsx, src/pages/Accounts/Accounts.tsx, src/pages/Accounts/components/AccountCard.tsx, src/pages/Accounts/components/AccountsTotalBalance.tsx, src/pages/Accounts/components/index.ts, src/pages/components/NetworkBalances.tsx, src/utils/index.ts, src/utils/table.ts
=> [WAL-486] Manage Accounts page.

src/components/Header/Header.tsx
- Close widget when goto manage accounts page only.
=> [WAL-472] Account Manager widget.

src/HOCs/withPageTitle.tsx, src/components/Header/Header.tsx, src/pages/CollectionPage/CollectionPage.tsx, src/pages/NFTDetails/NFTDetails.tsx
=> [WAL-497] Back link icon as Icon component

src/pages/CreateCollection/CreateCollection.tsx, src/pages/CreateNFT/CreateNFT.tsx, src/pages/CreateNFT/CreateNftForm.tsx, src/pages/components/FormComponents.tsx
Inc.:
- Forms;
- Headings and breadcrumbs.
=> feat: [WAL-485] - Create NFT page adaptive.

src/pages/Accounts/Modals/commonComponents.tsx, src/pages/CreateCollection/CreateCollection.tsx, src/pages/CreateNFT/CreateNFT.tsx, src/pages/CreateNFT/CreateNftForm.tsx, src/pages/components/FormComponents.tsx, src/pages/components/PreviewBar.tsx
- Drawer bottom bar dynamic height;
- ButtonGroup gap.
=> feat: [WAL-482] - Collection page adaptive.

package-lock.json, package.json, src/api/graphQL/collections/useGraphQlCheckInExistCollectionsByAccount.ts, src/api/graphQL/tokens/useGraphQlCheckInExistTokensByAccount.ts, src/api/graphQL/tokens/useGraphQlOwnerTokens.ts, src/api/restApi/hooks/index.ts, src/api/restApi/hooks/types.ts, src/api/restApi/hooks/useExtrinsicCacheEntities.tsx, src/api/restApi/hooks/useExtrinsicFlow/useExtrinsicFlow.ts, src/pages/CollectionNft/components/NftList/NftList.tsx, src/pages/CreateCollection/CreateCollection.tsx, src/pages/CreateNFT/CreateNFT.tsx, src/pages/MyCollections/MyCollections.tsx, src/pages/MyCollections/components/MyCollectionsList/MyCollectionsList.tsx, src/pages/MyTokens/NFTs/NFTs.tsx, src/pages/NFTDetails/Modals/BurnModal/BurnModal.tsx, src/pages/NFTDetails/Modals/TransferModal/TransferModal.tsx, src/pages/SendFunds/SendFunds.tsx, src/pages/components/ListEntitysCache/EntityItem.tsx, src/pages/components/ListEntitysCache/ListEntitiesCache.tsx, src/pages/components/ListEntitysCache/index.ts, src/pages/components/Nfts/NFTsTemplateList/NFTsTemplateList.tsx, src/pages/hooks/useCheckExistTokensByAccount.ts
=> feat: [WAL-534] - Optimistic UI

src/components/Confirm/Confirm.tsx, src/components/Modal/Modal.scss, src/components/Modal/Modal.tsx, src/pages/CreateCollection/constants.ts, src/pages/NFTDetails/Modals/BurnModal/AskBurnModal.tsx, src/pages/components/FormComponents.tsx
=> fix: [WAL-549] - modal NFT collection empty cover.

.env-example, src/pages/Accounts/Accounts.tsx
=> fix: [WAL-552] - correct url for uniq scan

src/components/CollectionScanLink/CollectionScanLink.tsx
=> fix: [WAL-538] - correct url for scan in collection

src/components/MobileTable/MobileTable.tsx
=> fix: [WAL-522] - Values attributes duplicated in mobile table

package-lock.json, package.json
=> up version sdk

src/api/restApi/balance/useAccountBalancesService.ts, src/pages/MyTokens/Coins/Coins.tsx
=> fix: [WAL-558] - change balance request by networks

src/App/App.tsx, src/components/IntroSlider/components/IntroCard.tsx
Co-authored-by: skozlov <skozlov@usetech.ru>
=> feat: [WAL-444] - Nested NFT Modals and adaptive.

src/components/Modal/Modal.scss, src/components/TooltipWrapper/TooltipWrapper.tsx, src/components/TooltipWrapper/index.ts, src/pages/Accounts/Accounts.tsx, src/pages/Accounts/Modals/Final.tsx, src/pages/Accounts/components/AccountCard.tsx, src/pages/CollectionPage/pages/CollectionSettings/CollectionSettings.tsx, src/pages/CreateCollection/tabs/AttributesTable.tsx, src/pages/CreateCollection/tabs/NFTAttributes.tsx, src/pages/FAQ/components/FaqItems.tsx, src/pages/FAQ/index.tsx, src/pages/NFTDetails/Modals/TransferModal/AskTransferModal.tsx, src/pages/NFTDetails/components/NFTDetailsHeader.tsx, src/pages/NFTDetails/components/TokenInformation.tsx, src/pages/components/FormComponents.tsx, src/pages/components/ModalComponents.tsx, src/styles/index.js
- Tooltips refs;
- zIndex tooltip modals.
=> fix: [WAL-486] - Tooltip fix.

src/components/Header/Header.tsx
- Hide mobile menu when change device size mobile -> desktop.
=> fix: [WAL-568] - Mobile menu fix.

src/pages/CreateCollection/tabs/MainInformation.tsx, src/pages/constants.ts
…ng of available fields maxlength
=> feat: [WAL-469] -  add max byte size validation collection form

src/components/Tags/Tags.tsx, src/components/Tags/components/Tag.tsx, src/components/Tags/index.ts, src/components/index.ts, src/pages/NFTDetails/components/TokenInformation.tsx, src/pages/components/Card/Card.tsx
- Tags;
- other components with Tags improved.
=> fix: [WAL-512] - Token inner page.

src/api/graphQL/collections/useGraphQlCollectionsByNestingAccount.ts, src/components/ActionBtn/index.ts, src/pages/NFTDetails/Modals/CreateBundleModal/CreateBundleModal.tsx
=> fix: [WAL-600] - not load empty collection on create nesting

src/pages/CreateCollection/CreateCollection.tsx, src/pages/CreateCollection/constants.ts
- Warn user via modal when attributes are empty.
=> fix: [WAL-590] - Add modal when empty attributes collection form.

src/pages/NFTDetails/components/NFTDetailsHeader.tsx, src/pages/NFTDetails/components/NftDetailsWrapperButtons.tsx, src/pages/NFTDetails/components/index.ts, src/pages/NFTDetails/page/NftDetailsBundlePage.tsx, src/pages/NFTDetails/page/NftDetailsPage.tsx, src/pages/components/BottomBar.tsx, src/pages/components/FormComponents.tsx
=> fix: [WAL-563] - My tokens, Token Page adaptive.

src/api/graphQL/tokens/useGraphQlCollectionTokens.ts, src/api/graphQL/tokens/useGraphQlOwnerTokens.ts, src/api/graphQL/types.ts, src/components/Achievement/Achievement.tsx, src/components/List/index.tsx, src/pages/CollectionNft/components/NftList/NftList.tsx, src/pages/MyTokens/NFTs/components/NFTsTemplateList/NFTsTemplateList.tsx, src/pages/components/TokenNftLink.tsx
=> task: [WAL-602] - visual separation of bundles and tokens

src/pages/NFTDetails/components/NFTDetailsHeader.tsx, src/pages/NFTDetails/components/NftDetailsCard.tsx, src/pages/NFTDetails/page/NftDetailsBundlePage.tsx, src/pages/NFTDetails/page/NftDetailsPage.tsx
=> fix: [WAL-603] - correct owned by in bundle/nested token

src/components/Filters/MobileFilter.tsx, src/pages/Accounts/Accounts.tsx, src/pages/CollectionPage/components/CollectionNftFilters/CollectionNftFilters.tsx, src/pages/components/Search.tsx
- In mobile filters;
- in desktop filters;
=> fix: [WAL-583] - Search height.

package-lock.json, src/components/AccountSelect/AccountSelect.tsx, src/components/AccountSelect/styles.ts, src/components/AccountsManager/AccountsManager.scss, src/components/AccountsManager/AccountsManager.tsx, src/components/AccountsManager/components/AccountsManagerDropdown/AccountsManagerDropdown.scss, src/components/AccountsManager/components/AccountsManagerDropdown/AccountsManagerDropdown.tsx, src/components/Header/Header.tsx, src/pages/Accounts/components/AccountCard.tsx
- Dropdown replaced with Select.
=> fix: [WAL-456] - Account manager dropdown.

package-lock.json, package.json, src/api/graphQL/tokens/useGraphQlGetTokensCollection.ts, src/api/graphQL/tokens/useGraphQlOwnerTokens.ts
=> Release v1.8.0
